version: "2"

services:

  microservice:
    depends_on:
      - mysql
    build: .
    links:
       - mysql:db
    ports:
     - "80:8080"

  mysql:
    image: registry.docker-cn.com/library/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
      - "./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:ro"
      - "./mysql/data:/var/lib/mysql"