
  # environment:
  #   - MYSQL_ROOT_PASSWORD=new    
version: "2"
services:

  microservice:
    depends_on:
      - mysql
    build: .
    links:
       - mysql:db
    ports:
     - "80:8080"

  mysql:
    image: registry.docker-cn.com/library/mysql
    # build:
    #   context: .
    #   dockerfile: DB-dockerfile
    # command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
      - "./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:ro"